### ISSUE TITLE
Internal Injection Mechanism for Plugin

### ISSUE THREAD

**Issue by ejemba** [nuun-io/kernel#1]
## Goal
Create a set of annotation/meta like @Init or @Nuun ... 

In order to inject special service to Plugins 

    @Required
    Plugin1 plugin1;

    @Dependent
    Plugin2 plugin2;

**Comment by ejemba** [comment]
Related to https://github.com/nuun-io/project-enhancement-proposals/blob/master/nuun-io_pep_002_plugin_plugin_api_modernization.adoc

**Comment by pith** [comment]
I'm not sure that we still want this feature. Your "trait" feature is much better I think. And the difference between `@Required` and `@Dependent` is not really obvious.

**Comment by ejemba** [comment]
@pith yes Trait plus the pep 003 will ease plugin development.
I close this one.
