### ISSUE TITLE
Clean UP Unused API

### ISSUE THREAD

**Issue by ejemba** [nuun-io/kernel#17]
Removing unused API to clarify or refactor them

1. [ ] From `@Ignore` to a Exclude API
1. [x] Removing `@Nuun`
1. [x] Renaming `RoundEnvironementInternal`
1. [x] Refactor `Context` & `ContextInternal`
    * [x] remove old methods
    * [x] add objectGraph

**Comment by pith** [comment]
Finally I'm not sure about the exclude API. Using kernel params in order to custum the root package seems enough for now.
Anyway if we can at least move this in another issue, this issue will fixed by 5dbab620fa282cdb61725328605e008eb7332cc8.
