### ISSUE TITLE
Possible bug with classpath scan ignore feature

### ISSUE THREAD

**Issue by pith** [nuun-io/kernel#34]
Currently all the classes annotated by an annotation ending with `Ignore` are ignored by the classpath scan. This might cause bugs hard to find. Because any annotation not necessarily related to Nuun or a framework based on Nuun can exclude a class from the scan. For instance `org.junit.Ignore` (It is not a good example but you see my point).

I think that the extensibility should be done by metaannotating an annotation with the Nuun `Ignore` annotation.

```
if (annotation.annotationType().equals(Ignore.class) ||  annotation.annotationType().getName().endsWith("Ignore"))
{
    toKeep = false;
}
```

https://github.com/nuun-io/kernel/blob/7aa955e65044869d6502d38c22557a0149b54d27/core/src/main/java/io/nuun/kernel/core/internal/scanner/AbstractClasspathScanner.java#L95

**Comment by ejemba** [comment]
@pith you are right. this feature was one of the first introduced. 
So your proposition make sense. 
Go for it !
