### ISSUE TITLE
Add the ability to iterate over kernel params

### ISSUE THREAD

**Issue by adrienlauer** [nuun-io/kernel#46]
In @seedstack, we want to use the kernel params to pass default configuration from the integration test (IT) runner to the IT plugin. We currently use system properties for that and their global scope is problematic. 

To be able to recognize the default configuration parameters we prefix them, but since we cannot iterate over all kernel params, it is impossible to retrieve only the prefixed params. Thus, we would like the ability to iterate over all kernel params from the InitContext. Something like:

    Map<String, String> allKernelParams = initContext.kernelParams();

**Comment by ejemba** [comment]
@adrienlauer Yes, we'll add this in the current modifications.
