### ISSUE TITLE
Disable Reflections log by default

### ISSUE THREAD

**Issue by pith** [nuun-io/kernel#47]
Currently, when the kernel scans by specification, it loads the classes in order to validate the specification. To do so, the ClasspathScannerDisk calls `ReflectionUtils.forNames(names, classLoader);`.

The issue is that when a class references a class which is not in the classpath, Reflections logs the error in `WARN`. It happens for instance when using optional dependencies with Maven.

Reflections provides a way to disable this log. At least, I suppose that it was the purpose when they decided to have a `@Nullable` public logger (cf. [javadoc](http://reflections.googlecode.com/svn/trunk/reflections/javadoc/apidocs/org/reflections/Reflections.html#log)). So the idea is to initialize this logger with `null` in the kernel and allow to enable it by a kernelParam.

**Comment by ejemba** [comment]
Seems completly legit.
