### ISSUE TITLE
Add the ability to retrieve scanned URLs

### ISSUE THREAD

**Issue by adrienlauer** [nuun-io/kernel#49]
To correctly implement diagnostic reporting, we need to have access to the real list of scanned URLs. With this list, the developer can more easily troubleshoot its runtime problems. 

We currently access to the list through reflection on the initContext. A public method (maybe on the initContext) would be an improvement.

**Comment by ejemba** [comment]
Yeah, this looks a usefull features to add. 
I also think for another issue providing the right classloader as well can make thing easier in some case, but that another issue.
